### PR TITLE
Updating agency ES rules

### PR DESCRIPTION
**Pull request by zhoudanxie**

### CODE REVIEW

**Comment by mfebrizio** [comment]
Working on this now!

Mark Febrizio
*Senior Policy Analyst* | Regulatory Studies Center
<https://regulatorystudies.columbian.gwu.edu/>
The George Washington University
***@***.***

**Review by mfebrizio — APPROVED** [review]
Great! I made a few minor changes to the code. The main one was accounting for the possibility of multiple whitespace characters in the regex, since it was failing to pick up one DHS rule.

**Comment by zhoudanxie** [comment]
> Great! I made a few minor changes to the code. The main one was accounting for the possibility of multiple whitespace characters in the regex, since it was failing to pick up one DHS rule.

Great catch! Thank you Mark!

**Comment by mfebrizio** [comment]
Oh, I didn't actually add that file. I just added one data point for 2023
(only went through 2022). We can remove it if it's not needed. I admittedly
didn't look that closely at where the presidential data was coming from,
but it was included in the pull request that I saw.

**Comment by mfebrizio** [comment]
Does this have to do with the code under "Re-organize existing datasets:
delete notes and add Presidential Party column" that's commented out?
Forgot to ask about that. I think we should remove that code if it's no
longer needed either.

**Pull request merged**
